// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'errors.freezed.dart';

@freezed
sealed class NwcError with _$NwcError implements FrbException {
  const NwcError._();

  const factory NwcError.persist({required String err}) = NwcError_Persist;
  const factory NwcError.generic({required String err}) = NwcError_Generic;
  const factory NwcError.network({required String err}) = NwcError_Network;
  const factory NwcError.pubkeyNotFound({required String pubkey}) = NwcError_PubkeyNotFound;
  const factory NwcError.invalidSignature({required String err}) = NwcError_InvalidSignature;
  const factory NwcError.encryption({required String err}) = NwcError_Encryption;
  const factory NwcError.eventExpired() = NwcError_EventExpired;
  const factory NwcError.alreadyReplied() = NwcError_AlreadyReplied;
  const factory NwcError.invoiceExpired() = NwcError_InvoiceExpired;
  const factory NwcError.invoiceWithoutAmount() = NwcError_InvoiceWithoutAmount;
  const factory NwcError.maxBudgetExceeded() = NwcError_MaxBudgetExceeded;
  const factory NwcError.connectionNotFound() = NwcError_ConnectionNotFound;
  const factory NwcError.connectionExists() = NwcError_ConnectionExists;
}

@freezed
sealed class PaymentError with _$PaymentError implements FrbException {
  const PaymentError._();

  const factory PaymentError.alreadyClaimed() = PaymentError_AlreadyClaimed;
  const factory PaymentError.alreadyPaid() = PaymentError_AlreadyPaid;
  const factory PaymentError.paymentInProgress() = PaymentError_PaymentInProgress;
  const factory PaymentError.amountOutOfRange({required BigInt min, required BigInt max}) =
      PaymentError_AmountOutOfRange;
  const factory PaymentError.amountMissing({required String err}) = PaymentError_AmountMissing;
  const factory PaymentError.assetError({required String err}) = PaymentError_AssetError;
  const factory PaymentError.invalidNetwork({required String err}) = PaymentError_InvalidNetwork;
  const factory PaymentError.generic({required String err}) = PaymentError_Generic;
  const factory PaymentError.invalidOrExpiredFees() = PaymentError_InvalidOrExpiredFees;
  const factory PaymentError.insufficientFunds() = PaymentError_InsufficientFunds;
  const factory PaymentError.invalidDescription({required String err}) = PaymentError_InvalidDescription;
  const factory PaymentError.invalidInvoice({required String err}) = PaymentError_InvalidInvoice;
  const factory PaymentError.invalidPreimage() = PaymentError_InvalidPreimage;
  const factory PaymentError.pairsNotFound() = PaymentError_PairsNotFound;
  const factory PaymentError.paymentTimeout() = PaymentError_PaymentTimeout;
  const factory PaymentError.persistError() = PaymentError_PersistError;
  const factory PaymentError.receiveError({required String err}) = PaymentError_ReceiveError;
  const factory PaymentError.refunded({required String err, required String refundTxId}) =
      PaymentError_Refunded;
  const factory PaymentError.selfTransferNotSupported() = PaymentError_SelfTransferNotSupported;
  const factory PaymentError.sendError({required String err}) = PaymentError_SendError;
  const factory PaymentError.signerError({required String err}) = PaymentError_SignerError;
}

@freezed
sealed class PluginStorageError with _$PluginStorageError implements FrbException {
  const PluginStorageError._();

  const factory PluginStorageError.dataTooOld() = PluginStorageError_DataTooOld;
  const factory PluginStorageError.encryption({required String err}) = PluginStorageError_Encryption;
  const factory PluginStorageError.generic({required String err}) = PluginStorageError_Generic;
}

@freezed
sealed class SdkError with _$SdkError implements FrbException {
  const SdkError._();

  const factory SdkError.alreadyStarted() = SdkError_AlreadyStarted;
  const factory SdkError.generic({required String err}) = SdkError_Generic;
  const factory SdkError.networkNotSupported({required String network}) = SdkError_NetworkNotSupported;
  const factory SdkError.notStarted() = SdkError_NotStarted;
  const factory SdkError.serviceConnectivity({required String err}) = SdkError_ServiceConnectivity;
}
