// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'events.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `on_event`

abstract class EventListener {
  Future<void> onEvent({required SdkEvent e});
}

class BreezEventListener {
  final RustStreamSink<SdkEvent> stream;

  const BreezEventListener({required this.stream});

  Future<void> onEvent({required SdkEvent e}) =>
      FlutterBreezLiquid.instance.api.crateEventsBreezEventListenerOnEvent(that: this, e: e);

  @override
  int get hashCode => stream.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BreezEventListener && runtimeType == other.runtimeType && stream == other.stream;
}

@freezed
sealed class SdkEvent with _$SdkEvent {
  const SdkEvent._();

  const factory SdkEvent.paymentFailed({required Payment details}) = SdkEvent_PaymentFailed;
  const factory SdkEvent.paymentPending({required Payment details}) = SdkEvent_PaymentPending;
  const factory SdkEvent.paymentRefundable({required Payment details}) = SdkEvent_PaymentRefundable;
  const factory SdkEvent.paymentRefunded({required Payment details}) = SdkEvent_PaymentRefunded;
  const factory SdkEvent.paymentRefundPending({required Payment details}) = SdkEvent_PaymentRefundPending;
  const factory SdkEvent.paymentSucceeded({required Payment details}) = SdkEvent_PaymentSucceeded;
  const factory SdkEvent.paymentWaitingConfirmation({required Payment details}) =
      SdkEvent_PaymentWaitingConfirmation;
  const factory SdkEvent.paymentWaitingFeeAcceptance({required Payment details}) =
      SdkEvent_PaymentWaitingFeeAcceptance;

  /// Synced with mempool and onchain data
  const factory SdkEvent.synced() = SdkEvent_Synced;

  /// Failed to sync with mempool and onchain data
  const factory SdkEvent.syncFailed({required String error}) = SdkEvent_SyncFailed;

  /// Synced with real-time data sync
  const factory SdkEvent.dataSynced({
    /// Indicates new data was pulled from other instances.
    required bool didPullNewRecords,
  }) = SdkEvent_DataSynced;
}
