// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'events.freezed.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BreezEventListener`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `on_event`

@freezed
sealed class SdkEvent with _$SdkEvent {
  const SdkEvent._();

  const factory SdkEvent.paymentFailed({required Payment details}) = SdkEvent_PaymentFailed;
  const factory SdkEvent.paymentPending({required Payment details}) = SdkEvent_PaymentPending;
  const factory SdkEvent.paymentRefundable({required Payment details}) = SdkEvent_PaymentRefundable;
  const factory SdkEvent.paymentRefunded({required Payment details}) = SdkEvent_PaymentRefunded;
  const factory SdkEvent.paymentRefundPending({required Payment details}) = SdkEvent_PaymentRefundPending;
  const factory SdkEvent.paymentSucceeded({required Payment details}) = SdkEvent_PaymentSucceeded;
  const factory SdkEvent.paymentWaitingConfirmation({required Payment details}) =
      SdkEvent_PaymentWaitingConfirmation;
  const factory SdkEvent.paymentWaitingFeeAcceptance({required Payment details}) =
      SdkEvent_PaymentWaitingFeeAcceptance;

  /// Synced with mempool and onchain data
  const factory SdkEvent.synced() = SdkEvent_Synced;

  /// Synced with real-time data sync
  const factory SdkEvent.dataSynced({
    /// Indicates new data was pulled from other instances.
    required bool didPullNewRecords,
  }) = SdkEvent_DataSynced;
}
