// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'errors.dart';
import 'frb_generated.dart';
import 'models.dart';
import 'nwc/event.dart';
import 'nwc/model.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'plugin.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BreezNwcService>>
abstract class BreezNwcService implements RustOpaqueInterface, Plugin {
  Future<AddConnectionResponse> addConnection({required AddConnectionRequest req});

  Stream<NwcEvent> addEventListener();

  Future<EditConnectionResponse> editConnection({required EditConnectionRequest req});

  Future<NostrServiceInfo?> getInfo();

  Future<void> handleEvent({required String rawEvent});

  @override
  Future<String> id();

  Future<bool> isZap({required String invoice});

  Future<List<Payment>> listConnectionPayments({required String name});

  Future<Map<String, NwcConnection>> listConnections();

  factory BreezNwcService({required NwcConfig config}) =>
      FlutterBreezLiquid.instance.api.crateNwcBreezNwcServiceNew(config: config);

  @override
  Future<void> onStart({required PluginSdk pluginSdk, required PluginStorage storage});

  @override
  Future<void> onStop();

  Future<void> removeConnection({required String name});

  Future<void> trackZap({required String invoice, required String zapRequest});
}
