// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'errors.dart';
import 'events.dart';
import 'frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PluginSdk>>
abstract class PluginSdk implements RustOpaqueInterface {
  Stream<SdkEvent> addEventListener();

  Future<GetInfoResponse> getInfo();

  Future<List<Payment>> listPayments({required ListPaymentsRequest req});

  Future<InputType> parse({required String input});

  Future<PrepareReceiveResponse> prepareReceivePayment({required PrepareReceiveRequest req});

  Future<PrepareSendResponse> prepareSendPayment({required PrepareSendRequest req});

  Future<ReceivePaymentResponse> receivePayment({required ReceivePaymentRequest req});

  Future<SendPaymentResponse> sendPayment({required SendPaymentRequest req});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PluginStorage>>
abstract class PluginStorage implements RustOpaqueInterface {
  String? getItem({required String key});

  void removeItem({required String key});

  void setItem({required String key, required String value, String? oldValue});
}

abstract class Plugin {
  Future<String> id();

  Future<void> onStart({required PluginSdk pluginSdk, required PluginStorage storage});

  Future<void> onStop();
}
