// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'event.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `on_event`

abstract class NwcEventListener {
  Future<void> onEvent({required NwcEvent event});
}

class BreezNwcEventListener {
  final RustStreamSink<NwcEvent> stream;

  const BreezNwcEventListener({required this.stream});

  Future<void> onEvent({required NwcEvent e}) =>
      FlutterBreezLiquid.instance.api.crateNwcEventBreezNwcEventListenerOnEvent(that: this, e: e);

  @override
  int get hashCode => stream.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BreezNwcEventListener && runtimeType == other.runtimeType && stream == other.stream;
}

class NwcEvent {
  final String? eventId;
  final String? connectionName;
  final NwcEventDetails details;

  const NwcEvent({this.eventId, this.connectionName, required this.details});

  @override
  int get hashCode => eventId.hashCode ^ connectionName.hashCode ^ details.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NwcEvent &&
          runtimeType == other.runtimeType &&
          eventId == other.eventId &&
          connectionName == other.connectionName &&
          details == other.details;
}

@freezed
sealed class NwcEventDetails with _$NwcEventDetails {
  const NwcEventDetails._();

  const factory NwcEventDetails.connected() = NwcEventDetails_Connected;
  const factory NwcEventDetails.disconnected() = NwcEventDetails_Disconnected;
  const factory NwcEventDetails.payInvoice({
    required bool success,
    String? preimage,
    BigInt? feesSat,
    String? error,
  }) = NwcEventDetails_PayInvoice;
  const factory NwcEventDetails.makeInvoice() = NwcEventDetails_MakeInvoice;
  const factory NwcEventDetails.listTransactions() = NwcEventDetails_ListTransactions;
  const factory NwcEventDetails.getBalance() = NwcEventDetails_GetBalance;
  const factory NwcEventDetails.getInfo() = NwcEventDetails_GetInfo;
  const factory NwcEventDetails.connectionExpired() = NwcEventDetails_ConnectionExpired;
  const factory NwcEventDetails.connectionRefreshed() = NwcEventDetails_ConnectionRefreshed;
  const factory NwcEventDetails.zapReceived({required String invoice}) = NwcEventDetails_ZapReceived;
}
