// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class AddConnectionRequest {
  final String name;
  final bool? receiveOnly;
  final int? expiryTimeMins;
  final PeriodicBudgetRequest? periodicBudgetReq;

  const AddConnectionRequest({
    required this.name,
    this.receiveOnly,
    this.expiryTimeMins,
    this.periodicBudgetReq,
  });

  @override
  int get hashCode =>
      name.hashCode ^ receiveOnly.hashCode ^ expiryTimeMins.hashCode ^ periodicBudgetReq.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AddConnectionRequest &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          receiveOnly == other.receiveOnly &&
          expiryTimeMins == other.expiryTimeMins &&
          periodicBudgetReq == other.periodicBudgetReq;
}

class AddConnectionResponse {
  final NwcConnection connection;

  const AddConnectionResponse({required this.connection});

  @override
  int get hashCode => connection.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AddConnectionResponse && runtimeType == other.runtimeType && connection == other.connection;
}

class EditConnectionRequest {
  final String name;
  final bool? receiveOnly;
  final int? expiryTimeMins;
  final bool? removeExpiry;
  final PeriodicBudgetRequest? periodicBudgetReq;
  final bool? removePeriodicBudget;

  const EditConnectionRequest({
    required this.name,
    this.receiveOnly,
    this.expiryTimeMins,
    this.removeExpiry,
    this.periodicBudgetReq,
    this.removePeriodicBudget,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      receiveOnly.hashCode ^
      expiryTimeMins.hashCode ^
      removeExpiry.hashCode ^
      periodicBudgetReq.hashCode ^
      removePeriodicBudget.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EditConnectionRequest &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          receiveOnly == other.receiveOnly &&
          expiryTimeMins == other.expiryTimeMins &&
          removeExpiry == other.removeExpiry &&
          periodicBudgetReq == other.periodicBudgetReq &&
          removePeriodicBudget == other.removePeriodicBudget;
}

class EditConnectionResponse {
  final NwcConnection connection;

  const EditConnectionResponse({required this.connection});

  @override
  int get hashCode => connection.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EditConnectionResponse && runtimeType == other.runtimeType && connection == other.connection;
}

class NostrServiceInfo {
  final String walletPubkey;
  final List<String> connectedRelays;

  const NostrServiceInfo({required this.walletPubkey, required this.connectedRelays});

  @override
  int get hashCode => walletPubkey.hashCode ^ connectedRelays.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NostrServiceInfo &&
          runtimeType == other.runtimeType &&
          walletPubkey == other.walletPubkey &&
          connectedRelays == other.connectedRelays;
}

class NwcConfig {
  final List<String>? relayUrls;
  final String? secretKeyHex;
  final bool? listenToEvents;

  const NwcConfig({this.relayUrls, this.secretKeyHex, this.listenToEvents});

  @override
  int get hashCode => relayUrls.hashCode ^ secretKeyHex.hashCode ^ listenToEvents.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NwcConfig &&
          runtimeType == other.runtimeType &&
          relayUrls == other.relayUrls &&
          secretKeyHex == other.secretKeyHex &&
          listenToEvents == other.listenToEvents;
}

class NwcConnection {
  final String connectionString;
  final int createdAt;
  final bool receiveOnly;
  final BigInt paidAmountSat;
  final int? expiresAt;
  final PeriodicBudget? periodicBudget;

  const NwcConnection({
    required this.connectionString,
    required this.createdAt,
    required this.receiveOnly,
    required this.paidAmountSat,
    this.expiresAt,
    this.periodicBudget,
  });

  @override
  int get hashCode =>
      connectionString.hashCode ^
      createdAt.hashCode ^
      receiveOnly.hashCode ^
      paidAmountSat.hashCode ^
      expiresAt.hashCode ^
      periodicBudget.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NwcConnection &&
          runtimeType == other.runtimeType &&
          connectionString == other.connectionString &&
          createdAt == other.createdAt &&
          receiveOnly == other.receiveOnly &&
          paidAmountSat == other.paidAmountSat &&
          expiresAt == other.expiresAt &&
          periodicBudget == other.periodicBudget;
}

class PeriodicBudget {
  final BigInt usedBudgetSat;
  final BigInt maxBudgetSat;
  final int? renewsAt;
  final int updatedAt;

  const PeriodicBudget({
    required this.usedBudgetSat,
    required this.maxBudgetSat,
    this.renewsAt,
    required this.updatedAt,
  });

  @override
  int get hashCode => usedBudgetSat.hashCode ^ maxBudgetSat.hashCode ^ renewsAt.hashCode ^ updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PeriodicBudget &&
          runtimeType == other.runtimeType &&
          usedBudgetSat == other.usedBudgetSat &&
          maxBudgetSat == other.maxBudgetSat &&
          renewsAt == other.renewsAt &&
          updatedAt == other.updatedAt;
}

class PeriodicBudgetRequest {
  final BigInt maxBudgetSat;
  final int? renewalTimeMins;

  const PeriodicBudgetRequest({required this.maxBudgetSat, this.renewalTimeMins});

  @override
  int get hashCode => maxBudgetSat.hashCode ^ renewalTimeMins.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PeriodicBudgetRequest &&
          runtimeType == other.runtimeType &&
          maxBudgetSat == other.maxBudgetSat &&
          renewalTimeMins == other.renewalTimeMins;
}
